export const Order_Create_data = {
  object: "order",
  id: "or_70920450",
  buyer_details: {
    address: {
      address_1: null,
      address_2: null,
      address_3: null,
      postal_code: null,
    },
    custom_questions: [],
    email: "samanthakudakolawa@gmail.com",
    first_name: "Kudakolawa Kaluarachchige Samantha",
    last_name: "Kaluarachchi",
    name: "Kudakolawa Kaluarachchige Samantha Kaluarachchi",
    phone: null,
  },
  created_at: 1770394825,
  credited_out_amount: 0,
  currency: {
    base_multiplier: 100,
    code: "gbp",
  },
  event_summary: {
    id: "ev_7508318",
    end_date: {
      date: "2026-02-14",
      formatted: "Sat 14 Feb 2026 10:30 PM",
      iso: "2026-02-14T22:30:00+00:00",
      time: "22:30",
      timezone: "+00:00",
      unix: 1771108200,
    },
    event_id: "ev_7508318",
    event_series_id: "es_2026024",
    name: "London Party Boat",
    start_date: {
      date: "2026-02-14",
      formatted: "Sat 14 Feb 2026 6:30 PM",
      iso: "2026-02-14T18:30:00+00:00",
      time: "18:30",
      timezone: "+00:00",
      unix: 1771093800,
    },
    venue: {
      country: "GB",
      name: "Westminster Pier",
      postal_code: "SW1A 2JH",
    },
  },
  issued_tickets: [
    {
      object: "issued_ticket",
      id: "it_115503530",
      add_on_id: null,
      barcode: "Tf3yNdR",
      barcode_url:
        "https://cdn.tickettailor.com/userfiles/cache/barcode/st/attendee/115503530/0d112186b7351e408603.jpg",
      checked_in: "false",
      created_at: 1770394977,
      custom_questions: [],
      description: "TicketGuru Test",
      email: "samanthakudakolawa@gmail.com",
      event_id: "ev_7508318",
      event_series_id: "es_2026024",
      first_name: null,
      full_name: null,
      group_ticket_barcode: null,
      last_name: null,
      listed_currency: {
        base_multiplier: 100,
        code: "gbp",
      },
      listed_price: 100,
      order_id: "or_70920450",
      qr_code_url:
        "https://cdn.tickettailor.com/userfiles/cache/barcode/qr/attendee/115503530/0d112186b7351e408603.png",
      reference: null,
      reservation: null,
      source: "checkout",
      status: "valid",
      ticket_type_id: "tt_5986341",
      updated_at: 1770394977,
      voided_at: null,
    },
  ],
  line_items: [
    {
      object: "line_item",
      id: "li_146834597",
      booking_fee: 0,
      description: "TicketGuru Test",
      item_id: "tt_5986341",
      quantity: 1,
      store_id: null,
      total: 100,
      type: "ticket",
      value: 100,
    },
    {
      object: "line_item",
      id: "li_146834677",
      booking_fee: 0,
      description: "TicketGuru Vip",
      item_id: "tt_5988141",
      quantity: 2,
      store_id: null,
      total: 300,
      type: "ticket",
      value: 150,
    },
  ],
  marketing_opt_in: null,
  meta_data: [],
  notes: null,
  payment_method: {
    id: "pm_177913",
    external_id: "acct_1SnHosQovdKy7lWT",
    instructions: null,
    name: null,
    type: "stripe",
  },
  referral_tag: "dsa",
  refund_amount: 0,
  refunded_voucher_id: null,
  sold_products: null,
  status: "completed",
  status_message: null,
  subtotal: 100,
  tax: 0,
  tax_treatment: "exclusive",
  total: 100,
  total_paid: 100,
  txn_id: "pi_3SxrlhQovdKy7lWT0A57XYlj",
};

export const eventsList = [
  {
    name: "Shreya Ghoshal Live in Birmingham",
    category: "Singer Event",
    start_time: "19:00:00",
    end_time: "22:00:00",
    venue: "Utilita Arena Birmingham",
    date: "2026-08-15",
    face_img: "shreya-ghoshal-birmingham.png",
    card_description:
      "Experience an unforgettable evening with Shreya Ghoshal performing her greatest hits live in Birmingham.",
    slug: "shreya-ghoshal-live-birmingham",
    sale: 0,
  },

  {
    name: "London Party Boat",
    category: "Boat Party",
    start_time: "20:00:00",
    end_time: "01:00:00",
    venue: "Thames River Pier",
    date: "2026-07-25",
    face_img: "boat_party.png",
    card_description:
      "Cruise through London's iconic skyline with live DJs, drinks, dancing, and amazing views.",
    slug: "london-party-boat",
    sale: 0,
  },

  {
    name: "Ife Business Networking Summit",
    category: "Business",
    start_time: "09:00:00",
    end_time: "17:00:00",
    venue: "London Business Centre",
    date: "2026-09-10",
    face_img: "ife-business-networking.png",
    card_description:
      "Connect with entrepreneurs, investors, and business leaders at one of London's premier networking events.",
    slug: "life-business-networking-summit",
    sale: 0,
  },

  {
    name: "Summer Music Festival",
    category: "Festival",
    start_time: "14:00:00",
    end_time: "23:00:00",
    venue: "Hyde Park",
    date: "2026-08-02",
    face_img: "default.png",
    card_description:
      "A full day of live music, food, entertainment, and unforgettable festival vibes.",
    slug: "summer-music-festival",
    sale: 0,
  },
];
