export const Order_Create_data = {
  id: "wh_3983627",
  created_at: "2026-02-06 05:23:25",
  event: "ORDER.CREATED",
  resource_url: "https://api.tickettailor.com/v1/orders/or_70895798",
  payload: {
    object: "order",
    id: "or_70895798",
    buyer_details: {
      address: {
        address_1: "The Queen's Walk",
        address_2: "Bishop's",
        address_3: "London",
        postal_code: "SE1 7PB",
      },
      custom_questions: [],
      email: "kasunchiwantha789@gmail.com",
      first_name: "Kasun",
      last_name: "Chiwantha",
      name: "Kasun Chiwantha",
      phone: null,
    },
    created_at: 1770355392,
    credited_out_amount: 0,
    currency: { base_multiplier: 100, code: "gbp" },
    event_summary: {
      id: "ev_7593708",
      end_date: [Object],
      event_id: "ev_7593708",
      event_series_id: "es_2049638",
      name: "Erabadu Wasanthaya",
      start_date: [Object],
      venue: {
        country: "GB",
        name: "Royal Albert Hall",
        postal_code: "SW7 2AP",
      },
    },
    issued_tickets: [[Object]],
    line_items: [[Object]],
    marketing_opt_in: null,
    meta_data: [],
    notes: null,
    payment_method: {
      external_id: "seller222@example.com",
      id: "pm_6691",
      instructions: null,
      name: null,
      type: "paypal",
    },
    referral_tag: "dsa",
    refund_amount: 0,
    refunded_voucher_id: null,
    sold_products: null,
    status: "completed",
    status_message: null,
    subtotal: 0,
    tax: 0,
    tax_treatment: "exclusive",
    total: 0,
    total_paid: 0,
    txn_id: "--",
  },
};
